apiVersion: v1 
kind: Service 
metadata:
   name: nginx-cl 
   namespace: Air 
spec: 
  selector: 
    app: nginx-dev 
  ports: 
    protocol: TCP 
    port: 80 
    targetPort: 80 


apiVersion: v1 
kind: Service
metadata:
  name: nginx-np 
  namespace: Air 
spec: 
  selector: 
    app: nginx-apps 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 30000 to 32767 
  type: NodePort 

apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-alb 
  namespace: Air 
spec: 
  selector: 
    app: nginx-apps 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer

apiVersion: v1 
kind: Service
metadata:
  name: nginx-apps 
  namespace: Air 
spec: 
  type: ExternalName 
  externalName: example.com

apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-hd 
  namespace: uk 
spec: 
  selector: 
    app: nginx-apps 
  ClusterIP: None 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
